name: 'ein_teil_von_mir'
url: 
description: '["data mining", "R", "machine learning", "python", "and more ..."]'

permalink: /:year/:month/:day/:title/
paginate: 10
highlighter: 'pygments'

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']